---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: asbest-os
description: Best OS ever

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
      - https://raw.githubusercontent.com/terrapkg/subatomic-repos/main/terra.repo
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
      - https://mise.jdx.dev/rpm/mise.repo
    install:
      # Development
      - automake
      - code
      - gcc
      - mise
      - zed
      # Dependencies
      - ncurses-devel
      - openssl-devel
      # Media
      - kdenlive
      - ffmpeg
      - gimp
      - vlc
      # System
      - btop
      - fastfetch
      - kate
      - mullvad-vpn
      - steam-devices
    remove:
      - nvtop
      - htop

  - type: default-flatpaks
    notify: true
    system:
      install:
        - io.github.zen_browser.zen
        - com.github.tchx84.Flatseal
        - com.usebottles.bottles
        - io.github.shiftey.Desktop
        - com.valvesoftware.Steam
        - com.atlauncher.ATLauncher
        - com.obsproject.Studio
    user: {}

  - type: signing
