---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: asbest-os
description: Best OS ever

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://gist.githubusercontent.com/MoeDevelops/84b0dbc28bc48bd03367756f34bed49a/raw/381cda8fc7803df601856ff87d0d81884e16ad47/vscode.repo
      - https://raw.githubusercontent.com/terrapkg/subatomic-repos/main/terra.repo
      - https://mise.jdx.dev/rpm/mise.repo
    install:
      # Development
      - automake
      - code
      - gcc
      - mise
      - zed
      # Dependencies
      - ncurses-devel
      - openssl-devel
      # Media
      - kdenlive
      - ffmpeg
      - gimp
      - vlc
      # System
      - btop
      - fastfetch
      - kate
      - steam-devices
    remove:
      - nvtop
      - htop

  - type: signing
