---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: asbest-os
description: Best OS ever

base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - kdenlive
      - fastfetch
      - ffmpeg
      - gimp
      - kate
      - steam-devices
      - vlc

    remove:
      - nvtop
      - htop
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      install:
        - io.github.zen_browser.zen
        - com.github.tchx84.Flatseal
        - com.usebottles.bottles
        - io.github.shiftey.Desktop
        - com.valvesoftware.Steam
        - com.atlauncher.ATLauncher
        - com.obsproject.Studio
    user: {}

  - type: signing
